### PR TITLE
Add remote testing on given ref

### PR DESCRIPTION
**Pull request by avishniakov**
This PR adds flexibility to testing action, so it can be called remotely out of the core.

### CODE REVIEW

**Comment by avishniakov** [comment]
@AlexejPenner , I feel ready to merge this 🙂 Can you approve/comment?

**Review by strickvl — APPROVED** [review]
Looks good to me, though I had to think for a while about what was meant by a git reference. Perhaps worth a comment or a short README in the `tests` folder to explain what's going on here?

**Comment by avishniakov** [comment]
> Looks good to me, though I had to think for a while about what was meant by a git reference. Perhaps worth a comment or a short README in the `tests` folder to explain what's going on here?

This is also confusing to me 🙂 Can you point me to the code line or file which caused your confusion? If you talk about `ref` - this is [a standard Git term for contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context). If it is something else, I would need your guidance to mitigate it.

**Comment by strickvl** [comment]
@avishniakov never mind, then! just betraying my ignorance. Then I think it's good to go. I'll read up on refs!

**Comment by AlexejPenner** [comment]
Retroactive approval from me as well :)

**Pull request merged**
